### PR TITLE
Fix a bug in the 3rd Exit Geofencing Notification.

### PR DESCRIPTION
**Pull request by breser**
Was wired up to 4th Car Enter Geofence notification.  Reported by Andyw2100 on TMC.

### CODE REVIEW

**Comment by breser** [comment]
Oops should have tried running with that fix.  Apparently that wasn't enough

    java.lang.NullPointerException
    	at org.noroomattheinn.visibletesla.NotifierController.initializeState(NotifierController.java:411)
    	at org.noroomattheinn.visibletesla.BaseController.activate(BaseController.java:114)
    	at org.noroomattheinn.visibletesla.MainController$5.run(MainController.java:314)
    	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:182)
    	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:179)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.sun.javafx.application.PlatformImpl$4.run(PlatformImpl.java:179)
    	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:76)

**Comment by breser** [comment]
Ok that should resolve that.  Sorry for the extra noise.

**Comment by jpasqua** [comment]
Testing now. Thanks.

**Comment by jpasqua** [comment]
Integrated in local copy by hand. Publishing soon. Thank you.

**Pull request closed without merging**
